### ISSUE TITLE
Snapcam seemed to go back to no filters showing, tried to patch again and it's saying unavailable

### ISSUE THREAD

**Issue by lyndiii** [jaku/SnapCameraPreservation#23] opened 2023-02-05 05:10 UTC
Hello! I went ahead and patched when snapcam shut down, had no issues until tonight when snapcam just seemed to go back to the never ending loading on the bottom and no filters showing up. I tried to patch again, seeing if my snapcam was just corrupted or something and when I go to patch it's saying the .dll program was not found. Is this just a me issue?

**Comment by jaku** [comment] 2023-02-05 06:14
This sounds like when you first patched the application you move it to the correct directory but ran it from there without replacing the original executable. So it worked until you closed the application or restarted. 

So now you're running the original unpatched executable. 

I'd recommend going back and starting the whole process over and make sure you do each step as outlined. 

The issue is with something you did or didn't do, the service is still working for others.

**Comment by lyndiii** [comment] 2023-02-05 06:38
I’ve already tried to do that, uninstalled and reinstalled, but when I go to patch the new install, when I try to open it it gives me the q5quick.dll file can not be found, says to uninstall etc. I had that error. Not sure what to do since I can’t patch because that error pops up every time

**Comment by jaku** [comment] 2023-02-05 07:42
You need to replace the original snap camera file. If you are not moving the patched file back to program files where you got the original exe it gives that error.

**Comment by lyndiii** [comment] 2023-02-05 15:35
Hmm, I try to do that. I uninstalled snapcam twice to try and patch it again, but when I do try to patch it it gives that error and I can’t even open the patched version to replace it because it gives that error, am I patching it wrong?

**Comment by jaku** [comment] 2023-02-05 23:55
Can you record your screen to show what you are doing? It sounds like you are getting that error when you select "Apply Patch" which shouldn't be happening.

**Comment by jaku** [comment] 2023-02-06 00:18
I've updated the patch site to have some more instructions and linked to 3 videos that should help.

I was able to reproduce your error by trying to open the patched file without moving it into the correct location. Please watch one of the videos and follow it step by step and you should be able to get this working again.

**Closed** 2023-02-06 22:32 UTC
