### ISSUE TITLE
Lens loading really slow + filters not getting applied

### ISSUE THREAD

**Issue by pWoLiAn** [jaku/SnapCameraPreservation#12] opened 2023-01-29 17:51 UTC
<img width="960" alt="image" src="https://user-images.githubusercontent.com/49567139/215345616-69256203-1eb8-4f89-ae50-7c1b516f51b5.png">

its taking ages for the filters to load and even after that, they are not getting applied. Is it possible that the server might have a geographical limitation?

**Comment by jaku** [comment] 2023-01-30 04:16
We use AWS to load the lenses, so it shouldn't have any geographical limitations. It could be a large number of users currently using the service for the first time, so it might be a good idea to try again and see if you have the same issue.

As for some lenses not loading, you'll see a little loading indicator on the snap lens icon on the right where the webcam image would be. If it doesn't go away, it's having an issue, but if it does go away and the lens still doesn't work, it's possible they didn't work in the original application either.

**Comment by pWoLiAn** [comment] 2023-01-30 04:34
As you can see from the screenshot, the snapcode wont stop loading. I am seeing this issue with literally every single lens that i've tried as well

**Comment by jaku** [comment] 2023-01-30 05:20
Yes, I also see that this was posted over 10 hours ago, which is why I asked for a recent update. I was merely letting you know how to determine if it was unable to load them, or if it was something else.

I see you are in the "Funny" category, I can confirm these are working for me. 

See if you are able to load this URL directly. https://s3.amazonaws.com/lens-storage-reversesnapcht.jaku.tv/png/040a215e-0e74-3c1f-9b20-a60bbc9675a3_320_28f12b7c-c97a-4267-9c93-f326dd2e1313.png

**Comment by rektubegaming** [comment] 2023-01-30 06:56
I have the same issue as @pWoLiAn too. It's just loading slowly and the lenses aren't applying when I clicked on them. Maybe the server is overloaded?
![image](https://user-images.githubusercontent.com/123929231/215408173-cfc54d1e-eb89-4662-82df-9cd52c45f3c4.png)
I tried loading the img link Jaku shared, it took me 5-7mins I think.

**Comment by jaku** [comment] 2023-01-30 07:17
What area of the world are you in? That's a direct link to Amazon S3 so it really shouldn't have an issue.

**Comment by jaku** [comment] 2023-01-30 07:21
It looks like I might need to implement Cloudfront to take advantage of the regional CDN network so that users outside the US won't have this issue.

**Comment by rektubegaming** [comment] 2023-01-30 07:26
> What area of the world are you in? That's a direct link to Amazon S3 so it really shouldn't have an issue.
> 
> There's not really a way to overload that server.

Good Question. I'm all the way from Malaysia, South East Asia. If that helps. xD

**Comment by jaku** [comment] 2023-01-30 07:31
Yep that explains it. Amazon S3 buckets can be extremely slow when outside the original region. My S3 bucket is based in the US so I'll need to setup some extra services to be able to serve the files faster outside the US. I'll work on getting this sorted out tomorrow.

**Comment by jaku** [comment] 2023-01-30 20:03
![image](https://user-images.githubusercontent.com/102187/215582949-e832f0b3-a66a-4a1d-b21c-7aeca21c15ee.png)
Using the current setup, this claims that it shouldn't be that bad. It's still much slower than US but should still be usable.

Still exploring the best option to replicate this, and it might just be throwing another bucket up in that region using the multi-region bucket support instead of CloudFront.

**Comment by jaku** [comment] 2023-01-31 00:54
Try this link. Let me know how it goes. If it's fast then I have the solution ready to deploy.

https://s3.ap-southeast-1.amazonaws.com/asia-lens-storage-reversesnapcht.jaku.tv/24d8c52a168e4ba68369eea4f4bbbe3b

**Comment by rektubegaming** [comment] 2023-01-31 01:09
> Try this link. Let me know how it goes. If it's fast then I have the solution ready to deploy.
> 
> https://s3.ap-southeast-1.amazonaws.com/asia-lens-storage-reversesnapcht.jaku.tv/24d8c52a168e4ba68369eea4f4bbbe3b

Yup, instant download to me now. I tried loading+applying the lenses and it works too. Many thanks man!

**Comment by jaku** [comment] 2023-01-31 03:07
Hey, @pWoLiAn let me know if you see the same thing now. I'll close the issue after getting confirmation.

**Comment by Kukiman0** [comment] 2023-01-31 21:42
Issue still persists for me (Poland). Lenses are not applying to my webcam view. I downloaded the upper links without any issues, they both downloaded in ~1s

**Comment by nnow991** [comment] 2023-02-01 03:40
> Issue still persists for me (Poland). Lenses are not applying to my webcam view. I downloaded the upper links without any issues, they both downloaded in ~1s

Poland as well - for me lenses works fine. So probably geographic location isnt the problem here

**Comment by phh95** [comment] 2023-02-01 14:57
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/29042617/216077275-0ab1cc4c-da71-4f77-9780-211903698a2d.png">
location：China
OS：macOS 13
VPN IP：Hong Kong

I follow your guide, but it seems doesn't work.

**Comment by jaku** [comment] 2023-02-03 16:05
For Windows users having issues, try downgrading to 1.19 and using the patch on my site for version 1.19.

That solved this issue for another user, and it's possible the bug was introduced in 1.21.

**Comment by jaku** [comment] 2023-02-05 00:59
Marking as completed due to no new posts.

**Closed by jaku** 2023-02-05 00:59 UTC

**Comment by TrippyQueen** [comment] 2023-02-07 10:17
> For Windows users having issues, try downgrading to 1.19 and using the patch on my site for version 1.19. https://sewro.com/public/download/snap-camera/27680396
> 
> That solved this issue for another user, and it's possible the bug was introduced in 1.21.

Hey Jaku! I’m from California and I’m also having issues but my issue seems different than what other people are experiencing. I’m able to run the patched program and the lenses show up but most of the filters look warped and some don’t work but add a white or colored box around my head so most are just unusable. I thought it was the 1.21 install but I tried the above link for 1.19 too and there were the same issues. I’ve included photos showing my issues. Thank yoy for making this all possible for us!

![4627D4FC-78B9-42F4-AA17-88D9325834C8](https://user-images.githubusercontent.com/124674090/217216995-922c647f-4d4d-4ce1-8e43-ffcb35af52bc.jpeg)
![9C3B5367-414A-44DF-9316-2317D5A3F102](https://user-images.githubusercontent.com/124674090/217217001-6519b8ff-68ab-4092-879e-0cce2e54fc71.jpeg)
![EEEE6706-4860-4008-938C-8C02AE1A1CED](https://user-images.githubusercontent.com/124674090/217217004-43968660-b5a6-4015-8b45-10907e8468fc.jpeg)
