### ISSUE TITLE
Lenses don't load with new MacOS update

### ISSUE THREAD

**Issue by dpkonofa** [jaku/SnapCameraPreservation#78] opened 2024-02-01 00:29 UTC
I reinstalled Snap Camera after getting a notification that there was a new solution for MacOS. I installed SC 1.21.0 from UpToDown and made sure all hosts entries and certificates were deleted prior to install.

Running the terminal command finished successfully, from what I can tell:
``This part will take a while. Please be patient.
/Applications/Snap Camera Temp.app: No such file or directory
Snap Camera has been patched!``

Opening Snap Camera post-install of the terminal script shows all the Jaku boxes and the lenses display in the list. Clicking a lens to activate it, though, just causes the QR code window to spin around, as if loading, but it never loads.

<img width="147" alt="Screenshot 2024-01-31 at 17 28 48" src="https://github.com/jaku/SnapCameraPreservation/assets/6332378/aeeb1d0b-9fc1-4e84-81da-504d0dbd4db1">

**Comment by jaku** [comment] 2024-02-01 19:14
So the script looks for the original Snap Camera app, copies it to Snap Camera Temp, and then patches the Temp version of the app before moving it back over the original.

Not sure how it couldn't copy that, but then was successful. 

As for the loading issue, I can't reproduce that either.

Try deleting the Snap Camera app from /Applications, then reinstalling it and running the script again.

**Comment by dpkonofa** [comment] 2024-02-01 22:49
@jaku - I already did that before install and two more times after. I even used AppCleaner to wipe all the old files. Still not getting anywhere. ☹️

**Closed** 2024-02-01 23:15 UTC
